version: '3.6'
services:

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rd-website
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build:
      args:
        PRECOMPILE_ASSETS: "false"
      context: .
      dockerfile: Dockerfile.web

    stdin_open: true # Keep the stdin open, so we can attach to it with byebug, etc.
    tty: true # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
